# Generated by Django 4.2.18 on 2025-02-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='commution',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
