# Generated by Django 4.2.18 on 2025-02-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_profitcalculator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profitcalculator',
            name='barcode',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
