INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Doğal Akasya 4 Gözlü Uzun Dekoratif Sunumluk Tabak Kase Çerezlik  13*40 cm', 'akasya05', 0, 649.0, 4);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Üçgen Top Ayaklı Ahşap Yükseltici Sunumluk Köşe Yağdanlık Altlığı 28*28*40 cm', 'stand05', 0, 479.0, 3);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('3lü Ahşap Top Kapaklı Cam Kavanoz  Baharatlık ve Saklama Seti 500-800-1400 ml Hacimli', 'baharatlık20', 0, 624.0, 9);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Bambu Peçetelik / Saklama Kutusu Sabitleyicili', 'peçetelik05', 0, 349.0, 5);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Hasır Rattan Peçetelik / Saklama Kutusu', 'peçetelik03', 0, 284.0, 5);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Hasır Rattan Peçetelik / Saklama Kutusu', 'peçetelik04', 0, 324.0, 5);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Akasya Standlı Cam Şık Kase Tabak Sunumluk Meyve/Salata/Çerez/Cips/Meze Kasesi 10*18 cm', 'kase04', 0, 915.0, 6);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Doğal Desenli Bambu Çerez/Cips/Meyve/Meze/Ekmek/Salata Kasesi Bowl Karıştırma Kabı Kasesi 10*17 cm', 'kase03', 0, 699.0, 9);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Doğal Bambu Dikdörtgen Sunumluk Tabak Servis Tabağı Kahvaltı Tabağı 13*28 cm', 'tabak02', 0, 299.0, 10);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Doğal Bambu Kare Sunumluk Tabak Servis Tabağı Kahvaltı Tabağı 25*25 cm', 'tabak01', 0, 349.0, 20);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('İçi Üç Boyutlu Renkli Hayvan Figürlü Tombul Cam Kupa Bardak 350 mL', 'figürlü09', 0, 370.0, 5);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Siyah Yanmaz Silikon Tencere Tava Kapağı 28-30-32 cm TEK KAPAK ÜÇ BOY TENCERE UYUMLU Buhar Tahliyeli', 'kapak02', 0, 569.0, 42);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Gri 6 Parça Silikon Yanmaz Yapışmaz Spatula Maşa Kaşık Servis Seti', 'grispatula01', 0, 549.0, 50);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Siyah Saplı Paslanmaz Çelik Börek Pasta Kek Pide Baklava Pizza Spatulası Servis Ekipmanı', 'çelik02', 0, 199.0, 48);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Mini Peynir Bıçağı Satır Bambu Ahşap Naturel Saplı Paslanmaz Çelik Uçlu Mutfak Gereçleri', 'mini03', 0, 199.0, 29);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Mini Rende Bambu Ahşap Naturel Saplı Paslanmaz Çelik Uçlu Mutfak Gereçleri', 'mini02', 0, 179.0, 30);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('4lü Ahşap Saplı Paslanmaz Çelik Gold Altın Yuvarlak Ölçü Kaşığı/Kalıbı 250/125/80/60 ml Hacimli', 'ölçü01', 0, 699.0, 15);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('2li Doğal Akasya 2 Gözlü Kısımlı Dikdörtgen Kase Tabak Çerezlik Sunumluk Sosluk', 'akasya02', 0, 499.0, 1);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Mini Bambu Ahşap Naturel Saplı Jülyen Soyacak  Paslanmaz Çelik Mutfak Gereçleri', 'mini05', 0, 174.0, 27);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Mini Şişe Açacağı Bambu Ahşap Naturel Saplı Paslanmaz Çelik Uçlu Mutfak Gereçleri', 'mini01', 0, 174.0, 26);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Yuvarlak Top Ayaklı Ahşap Yükseltici Sunumluk Yağdanlık Altlığı', 'sunumluk01', 0, 459.0, 12);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Siyah Saplı Paslanmaz Çelik Börek Pasta Kek Pide Baklava Pizza Spatulası Servis Ekipmanı', 'çelik03', 0, 124.0, 47);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Siyah Saplı Paslanmaz Çelik Börek Pasta Kek Pide Baklava Pizza Spatulası Servis Ekipmanı', 'çelik01', 0, 249.0, 45);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Doğal Akasya 4lü Kare Kase Tabak Çerezlik Sunumluk Sosluk', 'akasya01', 0, 429.0, 47);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Doğal Akasya 2 Gözlü Yuvarlak Kase Tabak Çerezlik Sunumluk Sosluk Dekoratif', 'akasya03', 0, 499.0, 48);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Doğal Akasya 3 Gözlü Yuvarlak Oval Kase Tabak Çerezlik Sunumluk Sosluk Dekoratif', 'akasya04', 0, 599.0, 50);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Mini Bambu Ahşap Naturel Saplı Pizza Kesme Aparatı Ruleti  Paslanmaz Çelik Mutfak Gereçleri', 'mini04', 0, 198.0, 15);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Şeffaf Akrilik 19 cm Büyük Boy Baharat Tuz Karabiber Öğütücü Değirmeni', 'değirmen02', 0, 299.0, 41);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('2li Şeffaf Akrilik 19 cm Büyük Boy Baharat Tuz Karabiber Öğütücü Değirmeni', 'değirmen01', 0, 549.0, 45);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('7li Bambu Ahşap Saplı Silikon Servis Seti Kepçe Kaşık Spatula Kevgir Makarna Süzgeci Çırpıcı Fırça', 'servis04', 0, 849.0, 28);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Silikon Mini ve Normal Kaşık Isıya Dayanıklı Yanmaz Yapışmaz Sert Uçlu', 'silikonset05', 0, 299.0, 49);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Silikon Mini ve Normal Kaşık Geniş Uçlu Köfte Spatulası Isıya Dayanıklı Yanmaz Yapışmaz Sert Uçlu', 'silikonset01', 0, 449.0, 50);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Silikon Mini ve Normal Kaşık Geniş Uçlu Köfte Spatulası Isıya Dayanıklı Yanmaz Yapışmaz Sert Uçlu', 'silikonset04', 0, 449.0, 50);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Silikon Mini ve Normal Kaşık Geniş Uçlu Köfte Spatulası Isıya Dayanıklı Yanmaz Yapışmaz Sert Uçlu', 'silikonset03', 0, 449.0, 50);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Silikon Mini ve Normal Kaşık Geniş Uçlu Köfte Spatulası Isıya Dayanıklı Yanmaz Yapışmaz Sert Uçlu', 'silikonset02', 0, 449.0, 50);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('İçi Üç Boyutlu Renkli Hayvan Figürlü Tombul Cam Kupa Bardak 350 mL', 'figürlü07', 0, 374.0, 4);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Ahşap Bambu 6 Bölmeli Kapaklı Çok Amaçlı Çay/Toka/Takı Kutusu Organizer 20 x 22 x 10 cm', 'kutu01', 0, 439.0, 2);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('İçi Üç Boyutlu Renkli Hayvan Figürlü Tombul Cam Kupa Bardak 350 mL', 'figürlü06', 0, 324.0, 8);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('İçi Üç Boyutlu Renkli Hayvan Figürlü Tombul Cam Kupa Bardak 350 mL', 'figürlü05', 0, 324.0, 1);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('İçi Üç Boyutlu Renkli Hayvan Figürlü Tombul Cam Kupa Bardak 350 mL', 'figürlü03', 0, 324.0, 7);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('İçi Üç Boyutlu Renkli Hayvan Figürlü Tombul Cam Kupa Bardak 350 mL', 'figürlü01', 0, 324.0, 11);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('İçi Üç Boyutlu Renkli Hayvan Figürlü Tombul Cam Kupa Bardak 350 mL', 'figürlü02', 0, 324.0, 20);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('3lü Bambu Ahşap Standlı Vakumlu Bambu Kapaklı Beyaz Cam Çay Şeker Kahve Kavanoz Seti 1000 mL', 'kavanoz12', 0, 925.0, 2);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('3lü Vakumlu Bambu Kapaklı Yazılı Beyaz Cam Çay Şeker Kahve Kavanoz Seti 1000 mL (TEA COFFE SUGAR )', 'kavanoz11', 0, 699.0, 2);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('3lü Buğulu Cam Sabunluk Pamukluk Diş Fırçalık Çok Amaçlı Organizerli Banyo Seti', 'sabunluk05', 0, 525.0, 5);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('2li Bambu Altlıklı Siyah Çubuklu Koku Şişeli Cam Sabunluk Banyo Seti 300 ml', 'sabunluk04', 0, 299.0, 6);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('6lı Gümüş İstiridye Sunum Çay Kaşığı 18/10 Paslanmaz Çelik', 'kaşık03', 0, 349.0, 50);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Ahşap Bambu Peçetelik Masaüstü Sofra Peçeteliği 12*14*6,5 cm', 'peçetelik01', 0, 229.0, 6);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Dikdörtgen 3lü  Kulplu Bambu Tepsi/Sunumluk 22*33/28*40/33*45', 'tepsi08', 0, 949.0, 1);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Dikdörtgen Orta Boy Kulplu Bambu Tepsi/Sunumluk 28*40 cm', 'tepsi06', 0, 425.0, 2);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Dikdörtgen Küçük Boy Bambu Kulplu Tepsi/sunumluk 23*34 Cm', 'tepsi05', 0, 375.0, 11);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('3lü Yuvarlak Kulplu Bambu Tepsi/Sunumluk 25-30-35 cm', 'tepsi04', 0, 1149.0, 13);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Delikli Küçük Kesme Tahtası  16*30', 'kesmetahtası01', 0, 249.0, 15);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Yuvarlak Büyük Boy Kulplu Bambu Tepsi/Sunumluk 35 cm', 'tepsi03', 0, 499.0, 15);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Yuvarlak Orta Boy Kulplu Bambu Tepsi/Sunumluk 30 cm', 'tepsi02', 0, 425.0, 15);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Küçük Yuvarlak Kulplu Bambu Tepsi/Sunumluk 25 cm', 'tepsi01', 0, 299.0, 15);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Bambu Ayaklı Sunum/Kesme Tahtası 4lü Ölçü Kabı ve 6lı Kaşıklı Kavanoz Baharatlık Seti', 'standset01', 0, 1250.0, 25);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Bambu Ahşap Peçete Kutusu Kağıt Mendil Masaüstü Peçetelik 23*11*9 cm', 'peçetelilk01', 0, 248.0, 36);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Siyah 4 Parça Silikon Spatula Kaşık Fırça Servis Seti', 'spatula05', 0, 399.0, 18);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Siyah 3 Parça Silikon Spatula Kaşık Servis Seti', 'spatula04', 0, 375.0, 17);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Siyah Silikon Spatula Maşa Fırça Servis Seti', 'spatula02', 0, 415.0, 20);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Siyah 6 Parça Silikon Spatula Maşa Kaşık Servis Seti', 'spatula03', 0, 499.0, 20);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('4lü Renkli Cam Pipet ve Temizleme Fırçası', 'pipet04', 0, 110.0, 20);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('6lı Renkli Cam Pipet ve Temizleme Fırçası', 'pipet03', 0, 124.0, 30);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Geniş Uçlu Silikon Spatula Köfte Spatulası 12 cm', 'spatula01', 0, 195.0, 99);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('6lı Bambu Kapaklı Vakumlu Silindir Cam Kavanoz Seti ve 6lı Ahşap Kaşık Seti (250 ml ve 200 ml )', 'kavanoz10', 0, 500.0, 48);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('6lı Bambu Kapaklı Vakumlu Silindir Cam Kavanoz Seti ve 6lı Ahşap Kaşık Seti (300 ml ve 250 ml )', 'kavanoz09', 0, 550.0, 20);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('3lü Yuvarlak Hasır Nihale 20 cm', 'nihale01', 0, 199.0, 100);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('6lı Yuvarlak Hasır Bardak Altlığı 10 cm', 'bardakaltlığı01', 0, 199.0, 100);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('3lü 250 mL Silikon Vakumlu Metal Paslanmaz Kapaklı Cam Kavanoz Seti', 'kavanoz08', 0, 449.0, 100);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('3lü 575 mL Silikon Vakumlu Metal Paslanmaz Kapaklı Cam Kavanoz Seti', 'kavanoz07', 0, 474.0, 100);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('3lü 810 mL Silikon Vakumlu Metal Paslanmaz Kapaklı Cam Kavanoz Seti', 'kavanoz06', 0, 524.0, 99);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('3lü 1300 mL Silikon Vakumlu Metal Paslanmaz Kapaklı Cam Kavanoz Seti', 'kavanoz05', 0, 549.0, 92);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Paslanmaz Peynir Dilimleyici ve Pasta Kek Pandispanya Teli', 'bıçak03', 0, 199.0, 100);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Paslanmaz Peynir Dilimleyici', 'bıçak02', 0, 114.0, 100);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Paslanmaz Pandispanya Kek Pasta Teli Kesici 33 cm', 'bıçak01', 0, 124.0, 97);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Siyah Yanmaz Silikon Tencere Tava Kapağı 20-22-24 cm TEK KAPAK ÜÇ BOY TENCERE UYUMLU Buhar Tahliyeli', 'kapak01', 0, 525.0, 35);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('6lı Paslanmaz Çelik (18/10) Uzun İnce Çay Latte Kaşığı', 'kaşık01', 0, 249.0, 98);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('6lı Paslanmaz Çelik (18/10) Uzun İnce Çay Latte Kaşığı', 'kaşık02', 0, 229.0, 99);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('2 Adet 750 ml  Hacimli Cam Su Şişesi Matarası', 'şişe09', 0, 449.0, 20);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('1 Adet 1000 ml (1 Litre) Hacimli Cam Su Şişesi Matarası', 'şişe06', 0, 324.0, 20);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('2 Adet 1000 ml (1 Litre) Hacimli Cam Su Şişesi Matarası', 'şişe08', 0, 464.0, 10);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('1 Adet 1000 ml (1 Litre) Hacimli Cam Su Şişesi Matarası', 'şişe07', 0, 324.0, 20);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('1 Adet 750 ml Hacimli Dalgalı Cam Su Şişesi Matarası', 'şişe05', 0, 299.0, 18);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('1 Adet 750 ml Hacimli Dalgalı Cam Su Şişesi Matarası', 'şişe04', 0, 299.0, 19);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Pembe Peluşlu 750 ml Hacimli Cam Su Şişesi Matarası', 'şişe03', 0, 199.99, 15);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Köpek Figürlü Gri Peluşlu 500 ml Hacimli Cam Su Şişesi Matarası', 'şişe02', 0, 184.99, 15);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('5li Bambu Saplı Silikon Servis Seti Kepçe Kaşık Spatula Kevgir Spatula Makarna Süzgeci', 'servis03', 0, 599.0, 29);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('5li Bambu Saplı Silikon Servis Seti Kepçe Kaşık Spatula Kevgir Spatula Makarna Süzgeci', 'servis01', 0, 599.0, 25);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('5li Bambu Saplı Silikon Servis Seti Kepçe Kaşık Spatula Kevgir Spatula Makarna Süzgeci', 'servis02', 0, 599.0, 28);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('6lı Bambu Ahşap Çerezlik Tabak Kase', 'kase02', 0, 499.0, 50);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('2li Bambu Ahşap Çerezlik Tabak Kase', 'kase01', 0, 199.0, 50);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('500 Ml Siyah-Beyaz Cam İkili Sabunluk Deterjanlık Mutfak Seti (Ahşap Stand Hediyeli )', 'sabunluk02', 0, 499.0, 12);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('500 Ml Siyah-Beyaz Cam İkili Sabunluk Losyonluk Banyo Seti (Ahşap Stand Hediyeli )', 'sabunluk01', 0, 499.0, 2);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('2li Gümüş Paslanmaz Çelik Pipet+ Temizleme Fırçası', 'pipet01', 0, 124.0, 100);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('6lı Gümüş Paslanmaz Çelik Pipet+ 3lü Temizleme Fırçası', 'pipet02', 0, 224.0, 99);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('1 Adet Büyük Bambu Ahşap Baharat Öğütücü Tuz-Karabiber Değirmeni', 'öğütücü03', 0, 349.0, 100);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('2li Büyük Bambu Ahşap Baharat Öğütücü Tuz-Karabiber Değirmeni', 'öğütücü02', 0, 599.0, 100);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('2 Bölümlü Gözlü Ahşap Bambu Çatal Kaşıklık Organizer Tezgah Üstü Düzenleyici 10*16*16 cm', 'kaşıklık01', 0, 399.0, 20);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Ahşap Bambu Kaşıklık Organizer Tezgah Üstü Mutfak Banyo Düzenleyici Kalemlik Fırçalık 10*13 cm', 'kaşıklık02', 0, 299.0, 13);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Beyaz Seramik 2li Ölçü Kabı Bardağı Seti 500/250 ml', 'ölçükabı02', 0, 349.0, 16);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Beyaz Seramik 4lü Ölçü Kabı Bardağı Seti 250/125/85/60 ml', 'ölçükabı01', 0, 449.0, 18);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('12 li 120 cc ml  Bambu Ahşap Kapaklı Cam Kavanoz Baharatlık Dökme Başlıklı  (16 lı Etiket Hediye)', 'baharatlık14', 0, 649.0, 10);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Ayaklı Yuvarlak Sunum Tahtası / Kesme Tahtası / Düzenleyici 30*30*8 cm', 'stand04', 0, 499.0, 20);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Ayaklı Dikdörtgen Ahşap Sunum Tahtası/Kesme Tahtası/Düzenleyici  33,5*22*8 cm', 'stand03', 0, 499.0, 19);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('5li 300 ml ve 5li 250 ml Cam Kavanoz ve İki  Katlı Ahşap Dönen Stand', 'baharatlık10', 0, 1424.0, 20);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('5li 250 ml ve 5li 200 ml Cam Kavanoz ile 10 Ahşap Kaşık ve İki  Katlı Ahşap Dönen Stand', 'baharatlık11', 0, 1274.0, 28);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('12li 120 ml Cam Kavanoz  Baharatlık ve  3 Katlı Bambu Stand (16lı etiket HEDİYE)', 'baharatlık18', 0, 1199.0, 30);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('12li 120 ml Cam Kavanoz  Baharatlık ve İki Katlı Döner Dönen Stand (16lı etiket HEDİYE)', 'baharatlık19', 0, 1249.0, 30);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('4lü 300 ml+4lü 250 ml+4lü 200 ml Vakumlu Yuvarlak Cam Kaşıklı Kavanoz ve 3 Katlı Bambu Stand', 'baharatlık15', 0, 1349.0, 29);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('4lü 300 ml Vakumlu Yuvarlak Kaşıklı Cam Kavanoz+12li 120 ml Baharatlık ve  3 Katlı Bambu Stand', 'baharatlık16', 0, 1549.0, 30);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('12li 300 ml Vakumlu Ahşap Kapaklı Cam Kavanoz Baharatlık,  12li Ahşap Kaşık ve 3 Katlı Ahşap Stand', 'baharatlık05', 0, 1499.0, 30);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('12li 200 ml Vakumlu Ahşap Kapaklı Cam Kavanoz Baharatlık,  12li Ahşap Kaşık ve 3 Katlı Ahşap Stand', 'baharatlık04', 0, 1249.0, 30);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('12li 250 ml Vakumlu Ahşap Kapaklı Cam Kavanoz Baharatlık ve 3 Katlı Ahşap Stand ile 12li Kaşık', 'baharatlık03', 0, 1349.0, 30);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('Yuvarlak Kulplu Mavi Çizimli Cam Şeffaf Bardak 200 mL', 'topkulplu01', 0, 199.0, 2);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('2li Doğal Bambu Ahşap Baharat Öğütücü Değirmeni Tuz Karabiber Öğütücü (Küçük)', 'baharatlık02', 0, 499.0, 100);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('1 Adet Doğal Bambu Ahşap Baharat Öğütücü Değirmeni Tuz Karabiber Öğütücü (Küçük)', 'baharatlık01', 0, 279.0, 100);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('6lı Yuvarlak Hasır Örme Jüt Amerikan Servis/Supla', 'amerikanser02', 0, 374.0, 100);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('250 cc Silikon Vakumlu Paslanmaz Kapaklı Cam Kavanoz', 'kavanoz01', 0, 165.0, 62);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('575 cc Silikon Vakumlu Paslanmaz Kapaklı Cam Kavanoz', 'kavanoz02', 0, 199.0, 64);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('1300 cc Silikon Vakumlu Paslanmaz Kapaklı Cam Kavanoz', 'kavanoz04', 0, 249.0, 90);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('810 cc Silikon Vakumlu Paslanmaz Kapaklı Cam Kavanoz', 'kavanoz03', 0, 214.0, 90);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('500 Ml Amber Gold Tıpalı İkili Yağdanlık', 'yağdanlık02', 0, 649.0, 4);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('500ml siyah cam ikili yağdanlık', 'yağdanlık0205', 0, 640.0, 4);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('500 Ml Gold İkili  Yağdanlık', 'yağdanlık03', 0, 649.0, 1);
INSERT INTO inventory_product (name, barcode, purchase_price, selling_price, stock) VALUES ('2li Hasır Amerikan Servis', 'amerikanser01', 0, 100.0, 2);